import base64
import io
import secrets
import socket
import string
import sys
import threading
import uvicorn
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Callable

import qrcode
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from jose import jwt

from app.api import auth, files, upload, web
from app.middleware.auth import AuthMiddleware


def _static_dir() -> Path:
    """Resolve app/web/static/ — works in dev and as a PyInstaller bundle."""
    if getattr(sys, "frozen", False):
        return Path(sys._MEIPASS) / "app" / "web" / "static"
    return Path(__file__).parent / "web" / "static"

def _qr_minutes() -> int:
    from app import config
    return int(config.load().get("qr_token_minutes", 5))

# In-memory session state — reset on every server start
session: dict = {
    "password": None,
    "jwt_secret": None,
    "port": None,
    "lan_ip": None,
    "qr_token": None,
    "qr_expires_at": None,
    "used_qr_tokens": set(),
}

_server_thread: threading.Thread | None = None
_uvicorn_server: uvicorn.Server | None = None
_qr_stop_event: threading.Event | None = None
_qr_reset_event: threading.Event | None = None
_on_qr_rotated: Callable | None = None


def set_qr_callback(fn: Callable | None) -> None:
    """Register a callback invoked every time the QR token is regenerated."""
    global _on_qr_rotated
    _on_qr_rotated = fn


def get_lan_ip() -> str:
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("8.8.8.8", 80))
            return s.getsockname()[0]
    except Exception:
        return "127.0.0.1"


def generate_qr_token() -> str:
    """Generate a fresh single-use QR token, print URL, notify UI callback."""
    minutes = _qr_minutes()
    jti = secrets.token_hex(8)
    expires_at = datetime.now(timezone.utc) + timedelta(minutes=minutes)
    payload = {
        "sub": "lanhopper-qr",
        "jti": jti,
        "exp": expires_at,
    }
    token = jwt.encode(payload, session["jwt_secret"], algorithm="HS256")
    session["qr_token"] = token
    session["qr_expires_at"] = expires_at

    url = f"http://{session['lan_ip']}:{session['port']}/?qr={token}"
    print(f"[LanHopper] QR URL (valid {minutes} min) →\n  {url}\n")

    if _on_qr_rotated:
        _on_qr_rotated(token, expires_at)

    return token


def build_qr_base64(token: str) -> str:
    """Return a base64-encoded PNG of the QR code for the given token."""
    url = f"http://{session['lan_ip']}:{session['port']}/?qr={token}"
    qr = qrcode.QRCode(version=1, box_size=6, border=3)
    qr.add_data(url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode()


def regenerate_qr() -> str:
    """Manually regenerate QR and reset the 5-min auto-rotation timer."""
    token = generate_qr_token()
    if _qr_reset_event:
        _qr_reset_event.set()
    return token


def _qr_rotation_loop(stop_event: threading.Event, reset_event: threading.Event) -> None:
    """Rotate QR every qr_token_minutes. Reset event restarts the countdown."""
    while True:
        reset_triggered = reset_event.wait(timeout=_qr_minutes() * 60)

        if stop_event.is_set():
            break

        if reset_triggered:
            reset_event.clear()
            # Token was already generated by regenerate_qr() — just restart timer
        else:
            # Natural 5-min rotation
            if session["jwt_secret"]:
                generate_qr_token()


def _build_app() -> FastAPI:
    app = FastAPI(title="LanHopper", docs_url=None, redoc_url=None)
    app.add_middleware(AuthMiddleware)
    app.mount("/static", StaticFiles(directory=str(_static_dir())), name="static")
    app.include_router(web.router)
    app.include_router(auth.router, prefix="/auth")
    app.include_router(files.router, prefix="/files")
    app.include_router(upload.router, prefix="/upload")
    return app


def start(port: int) -> str:
    global _server_thread, _uvicorn_server, _qr_stop_event, _qr_reset_event

    _charset = string.ascii_uppercase + string.digits
    session["password"] = "".join(secrets.choice(_charset) for _ in range(6))
    session["jwt_secret"] = secrets.token_hex(32)
    session["port"] = port
    session["lan_ip"] = get_lan_ip()
    session["used_qr_tokens"] = set()

    config = uvicorn.Config(_build_app(), host="0.0.0.0", port=port, log_level="warning")
    _uvicorn_server = uvicorn.Server(config)

    _server_thread = threading.Thread(target=_uvicorn_server.run, daemon=True)
    _server_thread.start()

    print(f"\n[LanHopper] Server started → http://{session['lan_ip']}:{port}")
    print(f"[LanHopper] Password       → {session['password']}")

    generate_qr_token()

    _qr_stop_event = threading.Event()
    _qr_reset_event = threading.Event()
    threading.Thread(
        target=_qr_rotation_loop,
        args=(_qr_stop_event, _qr_reset_event),
        daemon=True,
    ).start()

    return session["password"]


def stop() -> None:
    global _uvicorn_server, _qr_stop_event, _qr_reset_event

    if _qr_stop_event:
        _qr_stop_event.set()
        _qr_stop_event = None
    if _qr_reset_event:
        _qr_reset_event.set()
        _qr_reset_event = None

    if _uvicorn_server:
        _uvicorn_server.should_exit = True
        _uvicorn_server = None

    session.update({
        "password": None,
        "jwt_secret": None,
        "port": None,
        "lan_ip": None,
        "qr_token": None,
        "qr_expires_at": None,
        "used_qr_tokens": set(),
    })


def is_running() -> bool:
    return _uvicorn_server is not None and not _uvicorn_server.should_exit


def get_url() -> str | None:
    if not is_running():
        return None
    return f"http://{session['lan_ip']}:{session['port']}"
